employee_name=input("Enter employee name:")
employee_id=int(input ("enter employee id :"))
desigination=input("Enter employee desigination:")
salary=int(input("Enter employee salary:"))
bonus=int(input("enter employee bonous:"))
print(f"employee name is {employee_name} and employee id is {employee_id} and desigination of employee {desigination} and salary of an employee is {salary} and the bonus of employee is {bonus}")